### ISSUE TITLE
File to import not found or unreadable

### ISSUE THREAD

**Issue by renatocarvalho** [nextmat/compass-960-plugin#1]
When I try to make compass watch my project, I get the following error:

renato-carvalhos-macbook-pro-2:views renatocarvalho$ compass --watch static --trace

> > > Compiling all stylesheets.
> > > Sass::SyntaxError on line 80 of /opt/local/lib/ruby/gems/1.8/gems/haml-edge-2.1.24/lib/sass/files.rb: File to import not found or unreadable: 960/grid.sass.
> > >   /opt/local/lib/ruby/gems/1.8/gems/haml-edge-2.1.24/lib/sass/plugin.rb:204:in `dependencies'
> > >   /opt/local/lib/ruby/gems/1.8/gems/haml-edge-2.1.24/lib/sass/plugin.rb:203:in`map'
> > >   /opt/local/lib/ruby/gems/1.8/gems/haml-edge-2.1.24/lib/sass/plugin.rb:203:in `dependencies'
> > >   /opt/local/lib/ruby/gems/1.8/gems/haml-edge-2.1.24/lib/sass/plugin.rb:202:in`map'
> > >   /opt/local/lib/ruby/gems/1.8/gems/haml-edge-2.1.24/lib/sass/plugin.rb:202:in `dependencies'
> > >   /opt/local/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.15/lib/sass_extensions.rb:62:in`exact_stylesheet_needs_update?'
> > >   /opt/local/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.15/lib/compass/actions.rb:60:in `compile'
> > >   /opt/local/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.15/lib/compass/compiler.rb:38:in`run'
> > >   /opt/local/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.15/lib/compass/compiler.rb:37:in `each'
> > >   /opt/local/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.15/lib/compass/compiler.rb:37:in`run'
> > >   /opt/local/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.15/lib/compass/commands/update_project.rb:19:in `perform'
> > >   /opt/local/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.15/lib/compass/commands/watch_project.rb:14:in`perform'
> > >   /opt/local/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.15/lib/compass/commands/base.rb:15:in `execute'
> > >   /opt/local/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.15/lib/compass/commands/project_base.rb:19:in`execute'
> > >   /opt/local/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.15/lib/compass/exec.rb:197:in `do_command'
> > >   /opt/local/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.15/lib/compass/exec.rb:57:in`perform!'
> > >   /opt/local/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.15/lib/compass/exec.rb:40:in `run!'
> > >   /opt/local/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.15/bin/compass:8
> > >   /opt/local/bin/compass:19:in`load'
> > >   /opt/local/bin/compass:19

**Comment by renatocarvalho** [comment]
It was my mistake, I had started my project with Blueprint and later I changed to 960.gs. But the file config.rb wasn't updated and that's why I was getting this error. It's solved. Sorry.

**Comment by mattscilipoti** [comment]
Watch out for two config files (in root and config/)

**Comment by mattscilipoti** [comment]
You need: require 'ninesixty'
