### ISSUE TITLE
Option --using doesn't exist

### ISSUE THREAD

**Issue by oboxodo** [nextmat/compass-960-plugin#10]
The readme (and then github's project homepage) recommend to run compass using the '--using' parameter, but it doesn't exist in latest stable compass version. Any update on the docs?

Here's a run's output for you to evaluate.

$ gem list compass

**\* LOCAL GEMS ***

compass (0.8.17)
compass-960-plugin (0.9.11)
$ compass create -r ninesixty my_project --using 960
/home/diego/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/optparse.rb:1450:in `complete': invalid option: --using (OptionParser::InvalidOption)

**Comment by chriseppstein** [comment]
Sorry, those docs apply to the v0.10 release which is perfectly suitable for use, but not fully documented yet. to install it: gem install compass --pre, this will also require you upgrade you to sass 3, so you should read up on that if you're interested: http://nex-3.com/posts/95-awesome-syntax-changes-in-sass-3

closing.

**Comment by oboxodo** [comment]
Ah, yeah... I realized just after adding the issue.

I'm not wanting to upgrade to compass 0.10 and sass 3 yet, so I searched in your latest updates to readme and found the old command line which worked perfectly:

compass -r ninesixty -f 960 my_project
