### ISSUE TITLE
Importing 960 not working?

### ISSUE THREAD

**Issue by kjmears** [nextmat/compass-960-plugin#11]
@import 960/grid

Doesn't seem to work for me since upgrading to compass 0.10. It used to work 
with
@import 960/grid.sass

any suggestions?

**Comment by chriseppstein** [comment]
There's not much info to go on here. Did you upgrade your 960 gem?

Are you requiring it in your config?

Can you please post the relevant bits of your project for review?

Lastly, what versions of haml, compass, and 960?
Are you using compass with a framework like rails?

**Comment by kjmears** [comment]
Sorry for my rather brief speculative early question! I thought it would be rude not to reply. 

It seems that I had got myself into a bit of a pickle with bundler, and I couldn't be sure what gem version was running. I think I have sorted that out now and things look a lot better.
- compass (0.10.0.rc6)
- compass-960-plugin (0.9.13)
- haml (3.0.0.rc.5)

are what versions I'm running

I've run the convert with this command

sass-convert --in-place --from sass2 courses-home.sass
which seems to take of most things.

One question I have is i get this output before the declarations in my generated (compiled?) CSS. I guess something isn't quite right. not sure what I'm doing wrong though.

/\* line 17, ../../../../../.rvm/gems/ruby-1.8.7-p249/gems/compass-0.10.0.rc6/frameworks/compass/stylesheets/compass/reset/_utilities.scss */
body {
  line-height: 1;
  color: black;

  background: white;
}

**Comment by chriseppstein** [comment]
Don't feel too bad. About 10% of support requests turn out to be bundler issues :P

Regarding the comment, you didn't do anything wrong, that's just for debugging so you can find where some styles came from. you can turn it off in your config. Also, they'll be off automatically when you compile with style compressed or compact.
