### ISSUE TITLE
960.gs plugin is now out-of-date. Latest version is 1.5

### ISSUE THREAD

**Issue by shmuel** [nextmat/compass-960-plugin#13]
960.gs has been updated to 1.5 while this plugin remains at 1.0.

**Comment by nextmat** [comment]
After talking to Nathan Smith it looks like we're pretty feature-complete with the latest 960. Was there anything specific that you're missing that you'd like added?

**Comment by shmuel** [comment]
@mattsa Thanks for the note. I haven't looked at the 960 plugin in quite some time but it's great to hear that you have gotten it up-to-date.

**Comment by nextmat** [comment]
Going to close this for now, but if you come up with anything that needs updating, feel free to open a new issue.
