### ISSUE TITLE
 no such file to load -- ninesixty (LoadError) 

### ISSUE THREAD

**Issue by connor-t** [nextmat/compass-960-plugin#15]
after installing the plugin I get the error...

.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require': no such file to load -- ninesixty (LoadError)

require "ninesixty" is in config/compass.rb
gem "compass", ">= 0.10.6" is in my gemfile
rails 3.0.3

**Comment by chriseppstein** [comment]
did you add:

gem "compass-960-plugin" to your Gemfile?

**Comment by connor-t** [comment]
I did not and that fixes it, though it doesn't say anywhere in the docs to add it to the gemfile.

Thanks for the super quick response!

**Comment by chriseppstein** [comment]
Well there's a lot of ways to install gems. I assum that if you are using Bundler, you know that you have to reference all your gems there. Now you know :)
