### ISSUE TITLE
No such framework: "960"

### ISSUE THREAD

**Issue by ghost** [nextmat/compass-960-plugin#16]
hello,

i installed the plugin.
''sudo gem install compass-960-plugin
Successfully installed compass-960-plugin-0.10.0''

While command line 'compass -f blueprint test' works fine,
'rm -Rf test; compass -f 960 test' fails :
No such framework: "960"

what could be wrong ?

**Comment by ghost** [comment]
for information :
$compass --list-frameworks

yui
compass
blueprint

**Comment by ghost** [comment]
compass -r /var/lib/gems/1.8/gems/compass-960-plugin-0.10.0/lib/ninesixty.rb test2

is ok, but I had to import grid.sass and text.sass by hand
Hope it can help !

**Comment by chriseppstein** [comment]
The command you're looking for to create a compass project using 960 is specified in the readme. See for details:

https://github.com/chriseppstein/compass-960-plugin

**Comment by ghost** [comment]
I've read the docs before asking.

$ compass create -r ninesixty my_project --using 960

/usr/lib/ruby/1.8/optparse.rb:1450:in `complete': invalid option: --using (OptionParser::InvalidOption)

$ compass create -r ninesixty my_project

Create a directory called 'create' with src dir having ie.sass  print.sass  screen.sass, so not a 960gs project.

... I moved the plugins files (some) to /usr/share/compass/frameworks/ to be able to create a 960gs project with "compass proj2 -f 960"

I don't know why my install is different (?).

Ubuntu desktop 10-10 / Haml/Sass 3.0.9 (Classy Cassidy) / Compass 0.8.17 (all installed via gem install)

**Comment by chriseppstein** [comment]
The docs you are reading are for compass v0.10. Please upgrade.

**Comment by ghost** [comment]
Thanks for the support.

I'll give a last try... How can I get version 0.10 ?  (stuffs found googling did not helped me.)
Neither "sudo gem install chriseppstein-compass --source=http://gems.github.com" or "sudo gem install compass version=0.10.6" or "sudo gem install compass-edge" gave me the version 0.10" :(

(I should be miss-understanding something .¿ ...)

**Comment by nextmat** [comment]
You should be able to just 'sudo gem install compass' and get the most current version. Are you getting 0.8.17 with a straight gem install? What version of rubygems do you have installed?

**Comment by ghost** [comment]
$ gem --version 
1.3.7

$ compass --version
Compass 0.8.17

**Comment by nextmat** [comment]
Try upgrading your local version of rubygems to ensure you are pulling from the correct source:

gem update --system
gem update compass

**Comment by ghost** [comment]
thkx but

```
$ sudo gem update --system
```

ERROR:  While executing gem ... (RuntimeError)
gem update --system is disabled on Debian, because it will overwrite the content of the rubygems Debian package, and might break your Debian system in subtle ways. The Debian-supported way to update rubygems is through apt-get, using Debian official repositories.
If you really know what you are doing, you can still update rubygems by setting the REALLY_GEM_UPDATE_SYSTEM environment variable, but please remember that this is completely unsupported by Debian.

I won't take the risk. I'll try again in a few month...

thank you.

**Comment by nextmat** [comment]
When you type:

gem sources

What do you get?

**Comment by ghost** [comment]
$ gem sources
    **\* CURRENT SOURCES ***

```
http://rubygems.org/
```

**Comment by nextmat** [comment]
Not sure what your issue is. If you do figure it out, please let us know?

**Comment by ghost** [comment]
I'll let you know but for the moment, i will only use sass, witch is enough for me now now.
