### ISSUE TITLE
Provide option to use "grid-1" naming style instead of "grid_1"

### ISSUE THREAD

**Issue by mattyoung** [nextmat/compass-960-plugin#18]
grid-system() creates class names with "_". I want to use "-" instead. It would great if the separator character string is configurable so I can conform to our naming convention.   To be clear, I want instead of:

.grid_1, grid_2,,,,,,.prefix_1, .prefix_2

to be:

.grid-1, grid-2,,,,,,.prefix-1, .prefix-2

**Comment by nextmat** [comment]
I don't use the grid-system form much, but this should be an easy thing to write a patch for. 

You should just be able to add another $separator option to =grids, =grid-prefixes, and =grid-suffixes with the option on =grid-system to pass through to them. 

If you're still wanting this, but aren't sure how to get started, just drop me a line and I'll help you get going.

**Comment by mattyoung** [comment]
Thanks! I added this and sent the pull request.
