### ISSUE TITLE
reset.css of 960gs

### ISSUE THREAD

**Issue by puffy** [nextmat/compass-960-plugin#19]
Compass gem doesn't have good reset.css file applying reset for html 5 elements which contains in grid.sass. May be it possible to include reset.css of default 960-grid-system distribution?

**Comment by chriseppstein** [comment]
Compass has an html5 reset here:

http://compass-style.org/docs/reference/compass/reset/utilities/#mixin-reset-html5

**Comment by puffy** [comment]
Thanks, I missed it.
