### ISSUE TITLE
is this correct? @import compass/utilities/general/reset.sass 

### ISSUE THREAD

**Issue by jcnetdev** [nextmat/compass-960-plugin#2]
This throws an error for me

```
@import compass/utilities/general/reset.sass
+global-reset
```

However this works fine

```
@import compass/reset.sass
+global-reset
```

I'm using 0.9.7 and compass 0.8.10

Here is the error
Fri Aug 21 21:50:41 -0700 2009: Read error: #<Sass::SyntaxError: File to import not found or unreadable: compass/utilities/general/reset.sass.>

**Comment by chriseppstein** [comment]
That doesn't make much sense. Can you provide more details? What app framework or stand alone, etc?

**Comment by jcnetdev** [comment]
It's within a merb app. My thought is that the documentation is wrong. compass/utilities/general/reset.sass doesn't seem to be a valid path. Let me know if I'm wrong about this, I can debug it further.

**Comment by chriseppstein** [comment]
This works for me:

```
@import compass/utilities/general/reset.sass
+global-reset
```

It must be something about your config, maybe?

**Comment by chriseppstein** [comment]
Please verify that the file:

```
frameworks/compass/stylesheets/compass/utilities/general/_reset.sass
```

Exists in your compass installation. You can use the following command to locate compass if you don't know where it is:

```
compass --install-dir
```

**Comment by chriseppstein** [comment]
Going to close this issue without resolution soon. Let me know if you need a fix by providing more information.

**Comment by merbjedi** [comment]
Yep, you can close the issue. Thanks

**Comment by chriseppstein** [comment]
Thanks.

**Comment by alexslade** [comment]
I'm now having the exact same problem...

**Comment by chriseppstein** [comment]
I'm sorry to hear that can you provide any details?

**Comment by alexslade** [comment]
rails 2.3.4
haml 2.2.20
compass 0.8.17 , installed to /usr/local/lib/ruby/gems/1.8/gems/compass-0.8.17
compass 960 plugin

compass.config => http://gist.github.com/305317

**Comment by chriseppstein** [comment]
Please confirm: http://github.com/chriseppstein/compass-960-plugin/issues/issue/2#issue/2/comment/40954

**Comment by chriseppstein** [comment]
Meh. that didn't work very well. Please confirm:

Please verify that the file:

```
frameworks/compass/stylesheets/compass/utilities/general/_reset.sass
```

Exists in your compass installation. You can use the following command to locate compass if you don't know where it is:

```
compass --install-dir
```

**Comment by alexslade** [comment]
Yep that's there.

**Comment by chriseppstein** [comment]
Please show me the sass file where you try to import and use it.

**Comment by alexslade** [comment]
The standard grid.sass that was generated. http://gist.github.com/305323
It's at public/stylesheets/sass/grid.sass

I've been following the tutorial stuff to try and get the 960 framework running, haven't changed any code yet.
