### ISSUE TITLE
Where is clearfix??

### ISSUE THREAD

**Issue by sjoonk** [nextmat/compass-960-plugin#26]
I used this extention in my new project. Very helpful.

I found there is no clearfix declation in this plugin which exists on original 960 grid css stylesheet source.
The code is as follows:

/\* http://www.yuiblog.com/blog/2010/09/27/clearfix-reloaded-overflowhidden-demystified */

.clearfix:before,
.clearfix:after,
.container_12:before,
.container_12:after,
.container_16:before,
.container_16:after {
  content: '.';
  display: block;
  overflow: hidden;
  visibility: hidden;
  font-size: 0;
  line-height: 0;
  width: 0;
  height: 0;
}

.clearfix:after,
.container_12:after,
.container_16:after {
  clear: both;
}

/*
  The following zoom:1 rule is specifically for IE6 + IE7.
  Move to separate stylesheet if invalid CSS is a problem.
*/

.clearfix,
.container_12,
.container_16 {
  zoom: 1;
}

My question. Where is this clearfix in this compass-960-plugin?? 
How can I use this clearfix technique??

Thank you in advance.

**Comment by nextmat** [comment]
The reason I didn't port it is because the one that is in compass itself is very thorough and kept updated as new browsers are released. You can use it like:

```
.my_class
  +clearfix
```

Hope this helps!
