### ISSUE TITLE
Is there a mixin for the 960 text reset?

### ISSUE THREAD

**Issue by codecowboy** [nextmat/compass-960-plugin#27]
Firstly, thanks for providing this plugin ;-) I'm refactoring a php app to use compass and sass. Is there a mixin to use the 960 resets? You seem to be using the default compass reset in the wiki. Offering the scss syntax in the docs would be useful too!

**Comment by nextmat** [comment]
Glad you like it! There isn't a mixin for the 960 resets right now although we may add one later. If you really want it, you should be able to convert the reset css file from 960 easily using the sass tools. If you do, feel free to contribute back as you think appropriate.

I've been thinking about how to offer scss documentation as well, it is difficult to do without creating a maintenance headache with two versions to sync. Hopefully the documentation will be moving into the broader compass documentation systems which allow well for this.
