### ISSUE TITLE
Alpha, Omega

### ISSUE THREAD

**Issue by zd-dalibor** [nextmat/compass-960-plugin#28]
Alpha & Omega mixins only remove left or right margin and they do not add left or right margin width to column width.

**Comment by nextmat** [comment]
Can you give me an example of use which demonstrates this?

**Comment by zd-dalibor** [comment]
OK.
This is default values for 960-plugin:
$ninesixty-columns: 12
$ninesixty-grid-width: 960px
$ninesixty-gutter-width: 20px
$ninesixty-class-separator: '_'

This is two column grid with _N=6_ for both columns without alpha and omega:

<table>
<tr><td>gutter</td><td>column</td><td>gutter</td><td>gutter</td><td>column</td><td>gutter</td></tr>
<tr><td>10px</td><td>460px</td><td>10px</td><td>10px</td><td>460px</td><td>10px</td><tr>
</table>


Suppose we add alpha on first column

<table>
<tr><td>column</td><td>gutter</td><td>gutter</td><td>column</td><td>gutter</td><td>unused sapce</td></tr>
<tr><td>460px</td><td>10px</td><td>10px</td><td>460px</td><td>10px</td><td>10px</td><tr>
</table>

and shuld be:

<table>
<tr><td>column</td><td>gutter</td><td>gutter</td><td>column</td><td>gutter</td></tr>
<tr><td>470px</td><td>10px</td><td>10px</td><td>460px</td><td>10px</td><tr>
</table>


Suppose we add alpha on first column and omega on last column

<table>
<tr><td>column</td><td>gutter</td><td>gutter</td><td>column</td><td>unused sapce</td></tr>
<tr><td>460px</td><td>10px</td><td>10px</td><td>460px</td><td>20px</td><tr>
</table>

and shuld be:

<table>
<tr><td>column</td><td>gutter</td><td>gutter</td><td>column</td></tr>
<tr><td>470px</td><td>10px</td><td>10px</td><td>470px</td><tr>
</table>

**Comment by nextmat** [comment]
Thanks for the clarification, will investigate.

**Comment by nathos** [comment]
The +alpha & +omega mixins are meant for columns that are nested inside another column. Root-level columns don't need them to align properly.

**Comment by zd-dalibor** [comment]
This is the same situation as above. When you apply alpha or omega on nested column there will be an empty space in parent row.

**Comment by nextmat** [comment]
I know this is already closed, but as an addendum I chatted with Nathan Smith (creator of 960) about this and he confirmed that the behavior is correct.
