### ISSUE TITLE
Rails 3.1

### ISSUE THREAD

**Issue by garrensmith** [nextmat/compass-960-plugin#29]
Hey I just cant get this working with rails 3.1

Could you add a set in the readme or something to get this to work.
The error I'm getting is 
`File to import not found or unreadable: ninesixty/grid`

my gemfile is:
   gem 'compass', "~> 0.12.alpha.0"
   gem 'compass-960-plugin', '>0.10.4',:require => 'ninesixty'

**Comment by nextmat** [comment]
Can you show me the lines in your sass where you're using 960?

**Comment by garrensmith** [comment]
under `app/assets/stylesheets/grid.css.sass`
I have 
    @import compass
    @import compass/reset
    @import ninesixty/grid

**Comment by nextmat** [comment]
Change the final line to:

```
@import 960/grid
```

The library is called 'ninesixty' because ruby can't have imports that
start with numbers, but it is always used as '960' inside of sass.

On Mon, Nov 14, 2011 at 11:13 AM, garren smith
reply@reply.github.com
wrote:

**Comment by nextmat** [comment]
Closing, let me know if you have further issues.
