### ISSUE TITLE
Error when using  +grid-system(n) mixin

### ISSUE THREAD

**Issue by makenosound** [nextmat/compass-960-plugin#3]
I'm using Compass and the 960 plugin in a Staticmatic project and I get the following error if I try to use the `+grid-system(16)` mixin:

```
Fri Sep 25 16:03:56 +1000 2009: Read error: #<NoMethodError: private method `gsub' called for nil:NilClass>
(haml):17:in `render'
```

Doesn't happen with any of the other grid-mixins, just the container definition. Any ideas or is it likely a Staticmatic conflict of some sort?

Cheers,
Max

**Comment by chriseppstein** [comment]
cannot reproduce. Please provide additional details, if you can.
