### ISSUE TITLE
Ubuntu Oneiric nonfunctional 960 plugin

### ISSUE THREAD

**Issue by jvc26** [nextmat/compass-960-plugin#31]
I'm keen to use the plugin, but it doesn't appear to work on Oneiric.

I have:
- Compass 0.11.5 (Antares)
- Ruby 1.8.7
- Gem 1.7.2
- Compass-960-plugin 0.10.4

Available Frameworks & Patterns:

```
* blueprint
    - blueprint/project    - The blueprint framework.
    - blueprint/basic      - A basic blueprint install that mimics the actual blueprint css.
    - blueprint/semantic   - The blueprint framework for use with semantic markup.
    - blueprint/buttons    - Button Plugin
    - blueprint/link_icons - Icons for common types of links
* compass
    - compass/project      - The default project layout.
    - compass/ellipsis     - Plugin for cross-browser ellipsis truncated text.
    - compass/extension    - Generate a compass extension.
    - compass/pie          - Integration with http://css3pie.com/
* 960
    - 960/project          - The 960 Grid System.
```

In the config.rb I have

```
require 'ninesixty'
```

And in the top of my page.scss I have

```
@import 'compass/reset';
@import '960/grid';
```

However, whilst it imports the reset correctly, the grid is never loaded and no grid-related content is included in page.css. There are no outputted error messages. Why is this the case?

I realise I may have found the issue, does one also require:

```
.container_12 {
    @include grid-system(12); }
```

To make the system work?
Thanks

J

**Comment by nextmat** [comment]
Yep, the @import just makes the 960 mixins available. Once you include it you can pick between several ways to use it.

Take another look at the README, you can either include the entire grid (see Class-Based) or include grid components as mixins for your existing classes (see Making Semantic Grids).

Let me know if you run into any trouble. Hope this helps!
