### ISSUE TITLE
Wrong link to contributors in Readme file

### ISSUE THREAD

**Issue by ShPakvel** [nextmat/compass-960-plugin#33]
Hi Matt.
I've just noticed that link to contributors at the very bottom of Readme file is wrong.
Now it is:
https://github.com/chriseppstein/compass-960-plugin/contributors
But as I think it should be:
https://github.com/nextmat/compass-960-plugin/contributors

BR,
Pavel

**Comment by nextmat** [comment]
Thanks for the catch, fixed!
