### ISSUE TITLE
feature request: add pull, push classes

### ISSUE THREAD

**Issue by ghost** [nextmat/compass-960-plugin#5]
=grid-push(!n, !cols = !ninesixty_columns)
  :left= (!ninesixty_grid_width / !cols) \* !n

=grid-pushs(!cols = !ninesixty_columns)
  @for !n from 1 through !cols - 1
    .push_#{!n}
      +grid-push(!n, !cols)

=grid-pull(!n, !cols = !ninesixty_columns)
  :left= -(!ninesixty_grid_width / !cols) \* !n

=grid-pulls(!cols = !ninesixty_columns)
  @for !n from 1 through !cols - 1
    .pull_#{!n}
      +grid-pull(!n, !cols)

**Comment by chriseppstein** [comment]
Please submit a patch and I'll merge it in.

**Comment by chriseppstein** [comment]
this is added in v0.10.0.beta.0. I can't merge your branch because it doesn't apply anymore.
