### ISSUE TITLE
.clear/.clearfix missing?

### ISSUE THREAD

**Issue by sacrosby** [nextmat/compass-960-plugin#6]
There's some clearing code that is included in the 960 css files that I can't seem to find in the sass files in this plugin. Is it tucked in a partial somewhere or was it left out? 

sc

**Comment by chriseppstein** [comment]
.clear is just (clear: both) and is best handled in your stylesheets, not your markup. clearfix is a mixin provided by compass core, you can define .clearfix using it if you like or just mix it into your selectors as needed.

http://compass-style.org/docs/reference/compass/utilities/general/clearfix/

closing.
