### ISSUE TITLE
@import compass/utilities/general/reset.sass  throwing an error

### ISSUE THREAD

**Issue by alexslade** [nextmat/compass-960-plugin#8]
Same as a previous error, that line isn't happy. 

  File to import not found or unreadable: compass/utilities/general/reset.sass.

Any idea what could cause that? Sorry if I haven't included useful information, what would you like? 

Rails 2.3.4 using haml 2.2.20, compass 0.8.17 and the compass-960-plugin

**Comment by alexslade** [comment]
Ran into this again on my second attempt to use compass + 960, I sent you the details in a message (I can copy them here if need be).

**Comment by alexslade** [comment]
I was running the installer code: 
compass --rails -r ninesixty -f 960 . --css-dir=public/stylesheets --sass-dir=app/sass

When I stopped using the custom folders, it seems to work again. Why is this?

**Comment by chriseppstein** [comment]
fixed.
