### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by matjack1** [nextmat/compass-960-plugin#9]
i tried with the instructions provided but i couldn't install.

Instead using the command:

```
sudo gem install chriseppstein-compass --source=http://gems.github.com/
```

i had no problem!

**Comment by chriseppstein** [comment]
these instructions are wrong. where did you get them?

**Comment by matjack1** [comment]
with the instruction provided at the homepage: http://github.com/chriseppstein/compass-960-plugin i couldn't install the plugin, i got:
  http://github.com/chriseppstein/compass-960-plugin

so looking through internet i found the command posted. What's the right one?

**Comment by chriseppstein** [comment]
fixed. The readme instructions have been udpated, you'll need to upgrade to the latest version of haml and compass.

**Comment by matjack1** [comment]
thanks!! it works now :)
